defaults:
  - encoder: cnn_gru

model_name: siglab_nocontext

feature_dim: 128
signal_length: 1000
num_classes: 6
num_belief_updates: 5

classifier:
  in_size: 128
  layers:
    - out_size: 256
    - in_size: 256
      out_size: 256
    - in_size: 256
      out_size: 256
    - in_size: 256
      out_size: 128
    - in_size: 128
      out_size: 128
    - in_size: 128