model_name: sigloc-nolan
feature_dim: 64
signal_length: 1000

inception_block:
  branch1:
    out_channels: 16
  branch2:
    out_channels: 32
  branch3:
    out_channels: 32
  branch4:
    out_channels: 32
  branch5:
    out_channels: 32

inception_encoder:
  skip_connection: true  # Enable skip connection
  bottleneck_channels: 32
  num_blocks: 3
  dropout: 0.2

context_encoder:
  enabled: true
  hidden_dim: 64
  phi:
    num_layers: 4
    hidden_size: 64
  rho:
    num_layers: 1
  pooling: sum  # Sum pooling

classifier:
  layers:
    - out_size: 128
    - in_size: 128
      out_size: 64
    - in_size: 64
