defaults:
  - encoder: cnn_gru

model_name: siglab_deepsets

feature_dim: 128
signal_length: 1000
num_classes: 6
num_belief_updates: 5

deepsets:
  hidden_dim: 128
  phi_layers: 3
  rho_layers: 1

classifier:
  in_size: 256
  layers:
    - out_size: 256
    - in_size: 256
      out_size: 128
    - in_size: 128