name: cnngru

num_inception_blocks: 3
cnn_dropout: 0.2

gru:
  num_layers: 3
  bidirectional: false
  dropout: 0.3

inception_block:
  bottleneck_channels: 64
  branch1:
    out_channels: 32
  branch2:
    kernel_size: 5
    padding: 2
    out_channels: 32
  branch3:
    kernel_size: 11
    padding: 5
    out_channels: 32
  branch4:
    maxpool_size: 3
    out_channels: 32