name: inception

num_inception_blocks: 2
bottleneck_channels: 32
dropout: 0

inception_block:
  branch1:
    out_channels: 16
  branch2:
    kernel_size: 5
    padding: 2
    out_channels: 32
  branch3:
    kernel_size: 11
    padding: 5
    out_channels: 32
  branch4:
    kernel_size: 17
    padding: 8
    out_channels: 32
  branch5:
    maxpool_size: 3
    out_channels: 16