defaults:
  - model: siglabv2
  - dataset: ptbxl100all
  - optimizer: adam
  - scheduler: reduce_lr_on_plateau
  - loss: cross_entropy
  - wandb: default
  - augment: default
  - preprocessor_group: highpass_only
  - _self_

run:
  exp_num: "00" # Experiment number
  name: baseline # A short name for the experiment
  experiment_name: ${run.exp_num}_${model.model_name}_${run.name}
  comment: "baseline"
  epochs: 60
  batch_size: 32
  checkpoint: true
  min_delta: 0.001
  patience: 6
  checkpoint_path: checkpoints/${run.experiment_name}
  device: cuda
  log_level: info
  log_file: logs/${run.experiment_name}.log
  amp_dtype: float16 # Data type for AMP (Automatic Mixed Precision)

run_name: ${model.model_name}_${dataset.name}
